/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface _DrizzleMigrations {
  createdAt: number | null;
  hash: string;
  id: Generated<number>;
}

export interface Applicant {
  city: string | null;
  country: string | null;
  createdAt: Generated<string>;
  deletedAt: string | null;
  designation: Generated<string>;
  dob: string;
  email: string | null;
  firstName: string;
  fullAddress: string | null;
  gender: "female" | "male" | "other";
  id: Generated<number>;
  lastName: string;
  phone: string;
  relationshipStatus: "committed" | "single" | null;
  state: string | null;
  zipCode: string | null;
}

export interface Technologies {
  applicantId: number;
  createdAt: Generated<string | null>;
  deletedAt: string | null;
  id: Generated<number>;
  label: string;
  proficiency: "beginner" | "expert" | "intermediate" | null;
  updatedAt: Generated<string | null>;
}

export interface DB {
  _DrizzleMigrations: _DrizzleMigrations;
  applicant: Applicant;
  technologies: Technologies;
}
